--# un-ocean-de-secret
--Jeux de Rôle en ligne de commande futuriste
--
--##

histoire = {}

histoire[1] = "## Introduction ##\n"

histoire[2] = "J'étais dans la salle d'embarquement et je devais trouver la personne idéal rapidement, j'avais beau scruter chaque personne présente je ne voyais que des cyborgs don le taux de cybérnétisation n'était pas suffisant. Il y avait bien cette jeune femme mais... Et pis après tous c'était pour la bonne cause au tous du moins celle que je pensais juste. Je m'approchais d'elle, elle était jolie, l'age de sont enveloppe, bien que totalement supérflu était d'environs la trentaine. d'une qualité remarquable et qui plus ai bien entretenu. je lui injecta donc la dose de micro machine que j'avais préparé, elle ne senti rien au milieu de la foule si ce n'est que l'impréssion d'être piqué par un fermeture éclaire.\n"

histoire[3] = "Il ne me restait plus qu'a embarquer pour ma distination, la fameuse cité mère, celle dont tous le monde rêve d'aller, ne serai-ce que pour quelque jours de vacances. je passai le scanner d'identification sans encombre et commencai à me demander à quel moment les micro-machines commencerai à faire effet. l'idéal aurai été après avoir passé le scanner mais vue sont gabaris j'en fini pas en douter. Elle mis ça mains sur sont front à quelque mêtre du scanner, je savais qu'il n'y en avait plus pour que quelque seconde. Une personne proche lui adressa la parole, surement pour lui demander si quelque chose n'allais pas. Et, elle tomba à terre, comme évanouie bien que ce genre de chose était peut courant pour un cyborg. Une équipe de médecin et infiérmier arrive très vite sur place pour essayer de la réanimé, mais je savais bien sur qu'il n'y arriverai pas. Il l'emena sur un civière et la je commencer à frémir en moi. aller t'il l'emener à l'hospital le plus proche, aller t'il la faire embarquer et la mettre dans l'infiérmerie du vaisseau ? Ils commecerent à fouiller ses papier et je commencai à me dire que mon entreprise démarrais bien mal, non seulement elle n'avait pas passé\n"

histoire[4] = "le scanner, ni franchi l'étape qui lui aurai permis de faire parti du voyage mais en plus ils passèrent un temps fou à examiner ses papier comme si elle n'était pas en régle. Au final, et je ne sais par quel miracle il lui fis passé la barrière de securité pour la faire monter à bord du vaisseau. Je ne m'en était même pas rendu compte mais je n'eu pas la moindre réspiration durant ce laps de temps qui me parru pourtant bien long. Si bien qu'un autre passager me demanda si je la connaisser, je lui répondi bien évidament que non, ce qui était parfaitement le cas entre nous.\n"

histoire[5] = "Au fait je ne me suis pas présenté, je m'appel mat lionel, j'ai 37 ans et suis un cyborg à plus de 92%. Je gagne ou tous du moins je gagnais ma vie en travaillant comme mécanicien sur tous les types d'engin à moteur qu'il peut exister sous la surface de l'eau. Et oui vous avez bien entendu, la planète terre n'est plus qu'un immence océan du à la fonte des glaces des suite d'une guerre nucléaire. l'humanité n'a eu d'autre recours que de ce réfugier sous cette immence océan, bien froid et dénué de toute lumière du soleil. de toute façon à la surface il est fait telement chaud que vous y seriez grillé en quelque instant. J'utilise un module de journalisation pour laisser une trace de ce que je vais essayer de faire, de découvrir la vérité sur les raisons qui on conduit l'humanité et leurs plus haut dirigeant à appuyer sur le bouton qui déclancha une réaction en chaine nous condisant au tréfond de l'océan. Car aucun historique d'aucune sorte existe sur ce qu'était la planète terre avec cette catastrophe nucélaire, même le fait que je sache qu'il sagit d'un incident nucélaire, peut de gens le savent. Se sont tous au plus des suppositions de contoire. Car la vérité, c'est que tous a été étouffer et que quelque 60 ans après, les gens ne se pose même plus la question du pourquoi ils sont obliger de vivre dans des stations sous marine et que le seul moyens de transport son des vaiseaux sous marin. J'espere que ce module de journalisation ne sera pas détruit si je meurre et que le génération futur saurons réelement la vérité sur l'histoire de l'humanité.\n"

histoire[6] = "15 jour plus tôt...\n"

histoire[7] = "ça y est ! j'avais enfin mon billet pour la cité mère. J'avais du travailler pendant presque 3 mois pour pouvoir me le payer, sous le manteau il va de soi. Les personnes qui avait un billet pour la cité mère était soi des dirigeant, soi leur famille, soi des militaires. J'étais selon le descriptif fournis avec le billet le compagnion d'un homme d'affaire parti pour la cité mère signé des contrat avec l'armé. encore une semaine de boulot et je pourrai donner mon congès. Moi qui n'aimer pas les dimanche, je considérai celui ci comme un jour béni. J'avais récupéré mon billet dans un consigne dont la clé avait été laisser dans ma boite avec un mot m'expliquant ou trouver la consigne et les précaution que je devai prendre, chose que je savais déjà par coeur. Mes nombreux mois de chomage je les passai sur le réseau, enfin sur des réseaux du réseau. Ces réseaux été bien sur des réseau de cracker en tous genre ou pour y rester plus de dix minutes on devai avoir bien préparé sont kit de connexion sous peine de ce voir piraté ou au pire de ce faire frire la cervelle. Mais j'avais eu de bon professeurs, on rencontre tous à tas de gens lorsque l'on travail à la maintenance d'une station et vous seriez étonner des connaissances que ces gens peuvent avoir, alors que nous somme guer mieux considéré que les androides qui servent le café ou s'occupe des basse besogne. Alors que si nous n'étions pas la il n'y aurai point de cité sous marine fonctionnel car, l'aire qu'ils respire, l'eau qu'ils boivent, la lumière qui les éclaires ne serai pas, sans nous. Moi ma fonction c'est mécanicien de maintenance, grosso modo je répare tous ce qui est succéptible de tombé en panne et qui a au minimum un moteur electrique ou un turbine dans ça conception. Qu'a cela ne tienne, dans 15 jours se sera de l'histoire ancienne. J'avais tous préparé depuis plus d'un an, mais je savais que toute les préparation du monde ne pouvais me préparer à ce que j'allais vivre et ça commencer par un nouveau voyage, peut être le dernier...!\n"

histoire [8] = "Pour mon patron, je partait pour un autre station ou l'on avait besoin de moi, un poste mieux payé lui avais-je dit. Il n'a pas eu de mal à gober mon histoire mais je devais d'abort finir de réparrer ce fichu purificateur d'aire. l'une des modules avait lacher et comme la station ou j'étais comporter de nombreux bar de nuit ou il était autorisé de faire usage de tabac, l'aire de toute la station risquait de devinir rapidement noséabon si je ne fessai pas repartir ce module. Pour cela je devais déscendre au coeur du système de recyclage de la station, et fait paradoxale, c'était là que l'aire y était le moins bien recyclé. J'avais donc 15 jours pour réparer ce modules, Le boss m'avais donner carte blanche, autant au niveau équipement que droide de maintenance. Mais quand on se lancer dans un réparation, j'avais l'habitude de dire : 'On sais quand on commencer mais on sais pas quand on fini' car bien souvent il nous falait un pièce qui n'arriverai qu'au prochain ravitaillement, ou il fallait désactivé une partie du système et on ne pouvais dès lors que travailler la nuit ( notion quelque peut relative lorsque la seul vison qu'on ai de l'extérieur c'est un masse d'eau toute noir que même les projecteur peine à pénétrer, projecteur uniquement désitné à identifier les animaux aquatique potentiellemnt dangereux pour la station).\n"

histoire[9] = "Bien que j'eu mis toute mes fonction non essentiel un veille, je n'arriva pas à fermé l'oeil jusqu'a la sonnerie de mon ancestral réveil. je réactiva donc mes fonction en commencant par la vision en prennant le temps de bien vérifier leur configuations. Je pris ma ration alimentaire du matin, les cyborgs devaient manger des aliments bien spécifique sous peine de sérieux problème et disfonctionnement. Et pris le chemin du dépot.\n"

histoire[10] = "Arrivé sur place, seul le boss été déjà là. Je finisai par croire qu'il prennait ses heure de repos sur place, il était toujours le dérnier partie et le premier arrivé. Je mis ma tenu de travail et commencai à lancer les test de contôle des 2 droide que j'avais prévu pour la journée. Je vérifier également l'état de leur batterie et fis un checkup visuel complet. Il n'était pas de première jeunesse et avait déjà bien servi mais il était en état. un fois leur intelligence artificiel démarré et opperationnel je les connecta à mon système de contôle et pris le premier assenseur d'unn longue, très longue suite d'ascenseurs, nécessaire pour aller jusqu'au coeur du système de recylage...\n"

histoire[11] = "Après un bonne heure passé dans les ascenseur, les passerelles et les sas, à rentré à chaque fois les même code d'accès, code qui m'était presonnel et qui pouvait aussi bien m'autorisé un accès tous comme me le refuser, j'étais enfin arrivé. je du désactivé mes fonction auditive telement le bruit y été assourdissant, ainsi que je du metter en place mon module de filtrage de l'aire car de nombreuses vapeur et polluant était présent dans l'atmosphère. Il me falait maintenant identifier le module en question parmis un bon millier d'équipement, je savais qu'il se trouver au niveau 54 sur la passerelle 38, et heureusement que j'avais un sacrée sense de l'orientation car une personne non préparé n'aurai eu aucun mal à ce perdre au milieu de toute cette machinerie.\n"

histoire[12] = "J'etais devant le module en panne, je commença par regarder les differents voyant et indicateur, il ne m'apprenais rien de nouveau, le module ne filtrai plus les particule de dioxyde de carbone, mais pour quel raison, c'est ce que je voulais découvrir au plus vite pour pouvoir faire mes bagage pour la cité mère. Je me branchais directement sur le calculateur et lanca un batterie de teste, tous confirmière la même chose et je n'était pas plus avancer. je devais aller au poste de transmission le plus proche pour informé le poste de contrôle que je désactive ce module et que j'allais lui ouvrir les entrailles. Une fois fait je commenca par faire démonté les grille et autre capot de protection par les droides et je mi la tète directement dans la mécanique, j'étais habituer mais un bleu s'y serai pris à deux fois et aurai au  moins vérifier trois autre fois s'il avait bien désactivé tous le bazard. et finalement j'avais trouver la panne, encore un truc qu'une intelligence artificiel, quelque soi sa capacité de calcul n'aurai jamais trouver. Ce n'étais ni plu ni moins qu'un préservatif qui était passé je ne sais comment par le système de ventilation et avait obstrué la sonde premettant de controler le niveau de dioxide. J'étais ravis, cette réparation ne m'avais même pas pris la matiné. juste 5 min au deux droide pour remonter tous les systèmes de sécurité et un bonne heure pour remonté au dépot expliqué le problème au boss pour qu'il demande au poste de contôle de relancer les testes et de refaire partir le module de filtrage.\n"

histoire[13] = "J'étais arrivé dans ma cabine, je savais que cette jeune femme que j'avais choisi avait été conduit elle aussi à bord. d'ailleur je me demande encore pourquoi. Maintenant je devais agir rapidement et en toutes discrétion, mais quelque scrupule me tarodé l'esprit. Je fis en sorte de ne pas leur laisser libre cours et de resté concentré sur mes objectif. Je devais déjà sécurisé mon terminal d'accès et masquer les traces de ce que j'allais faire. Pour cela j'avais sauvegarder dans ma mémoire interne toute un procédure minusieusement préparé. Je me mis à la tache sans attendre, le vaisseau sous marin avait déjà largé ses amard depuis un bonne heure et le trajet était quand même relativement cours. Je me connecta à mon terminal dérrier un module proxy pour ne pas laisser d'emprinte neuronnale et commença le piratage de divers terminal et personne connecter au hazard, je devais crée autant de liens que possible pour que l'on ne puisse pas remonter jusqu'a moi, tous du mon que l'on ne sache ce que j'avais fait. Car il resterai de toute façon mon corps inerte que serai découvert tôt ou tard et une enquète sera lancer alors pour connaitre les raison de la destruction pur et simple de mon cerveau et de l'effacement de l'intégralité de ma mémoire, y compris tous les accès externe auquel j'avais accès depuis ce vaisseau. De toute façon il ne restait plus beaucoup d'accès exterieur puisque je les avais tous minutieusement supprimé de façon radicale et discrette.\n"

histoire[14] = "Bon j'avais relier suffisament de liens pour commencer l'opération, là phase deux de mon plan pour ne plus être identifiable. Je n'accèda sans mal à l'infiérmerie et un rapide passage par le registre des personne présente me donna le chemin pour accèder à cette jeune fille, qui malheureusement n'avait rien demander pour y être. J'étais connecté à sont cerveau, les micro machine que je lui avais injecté et qui avait provoqué sont évanouissement avait été programmer également pour me laisse un passage dans les plus profond accès de sont cerveau. Je ne pris pas le temps d'annalyzer les caractèristique de celui ci, ni même j'eu pris le temps de relever sont identié ou sont secteur professinnel. je devais faire vite, les information manquante je les trouverai par la suite. Je me connecta à ses fonction visuel et auditive et je fus suppris par la qualité de la réception mème à traver le labyrinte que j'avais tracer parmis un grand nombre de voyageur du vaiseau. J'allais lancer la procédure d'effacement et de transfère losrque je fu pris d'un incoyable dilème. Prendre le corps de quelqu'un d'autre été un chose, detruire l'integralité de sa mémoire et donc la personne elle même en été un autre. Je n'eu que quelque second pour réfléchir à ce problème car un deamon d'analyse me se mi à m'alerté qu'un de mes liens était sur le point de flanché, certainement la compagne ou le compagnon de cette presonne été retourner dans leur cabine et avait vue cette personne dans un état proche de l'hypnose et avait alareté la sécurité. Qu'a cela ne tiens, je décida de faire un sauvegarde compresser de l'intégralité de la mèmoire de cette jeune femme, car la capacité de sont cerveau le premettait et que je lui redonnerai sont corps, ou à défaut un autre un fois mes objectif atteint. bizarment l'opération ne pris que quelque seconde et je commencer à croire qu'au vue des capacité de sont cerveau cybernétique je n'avais pas fait un si mauvais choix.\n"

histoire[15] = "Plus que quelque seconde avant tracasse vers le point d'entré. Je ne pouvais plus reculer, tous les indicateur été au rouge et j'allais être repéré. je laça la dernier phase de ma procédure et copia l'intégralité de ma mémoire dans cette jeune femme avant de lancer un virus destructeur sur mon ancien corps qui était aussi efficace que totalement illégale. je me retrouvis d'un coups d'une seul dans une sorte d'absence, de sommeil cataléptique, c'était le noir totale...\n"


